Set the puppet-agent version for gem package install
Since puppet-agent gem version is relied on the ruby version, we have
to specify the version for them, otherwise `gem install` will try to
install the latest one, which will lead to error:

ERROR:  Error installing puppet:
The last version of puppet (>= 0) to support your Ruby & RubyGems
was 7.26.0. Try installing it with `gem install puppet -v 7.26.0`
puppet requires Ruby version >= 3.1.0. The current ruby version is 2.7.0.0.

The ruby and puppet-agent support version matrix can be found in
https://www.puppet.com/docs/puppet/6/platform_lifecycle.html
https://www.puppet.com/docs/puppet/7/platform_lifecycle.html
as bionic uses v2.5 Ruby and focal uses v2.7 Ruby.

Change-Id: I6aa949d54cb007cd9f66d680f11e71b540122c26